apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    title: my-app
    type: web-app
spec:
  containers:
    - name: my-container
      image: javabyraghu/maven-web-app
      ports:
        - containerPort: 8080
